# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-09 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=254)),
                ('restaurant_url', models.CharField(max_length=254)),
                ('restaurant_location', models.CharField(max_length=254)),
                ('restaurant_rating', models.CharField(max_length=254)),
            ],
        ),
    ]
